apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: learning-three-teir
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-infra
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
