apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nivashub-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: learning-three-teir
  source:
    repoURL: https://github.com/AayushChauhan1916/K8_3_TIER_FULL_APP.git
    targetRevision: main
    path: services/nivashub
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nivashub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
