apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: three-tier-services
  source:
    repoURL: https://github.com/AayushChauhan1916/K8_Mongo_Operator_and_three_tier-application.git
    targetRevision: main
    path: services/frontend
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nivashub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
