apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-namespaces
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: three-tier-infrastructure
  source:
    repoURL: https://github.com/AayushChauhan1916/K8_Mongo_Operator_and_three_tier-application.git
    targetRevision: main
    path: infrastructure/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
