global:
  name: nivashub-frontend
  environment: dev

replicaCount: 2

image:
  repository: ishan420/frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
