apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.global.name }}-deployment
  labels:
    app: {{ .Values.global.name }}
    component: backend
    resource: deployment
    env: {{ .Values.global.environment }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        env: {{ .Values.global.environment }}
        component: backend
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- toYaml .Values.env | nindent 12 }}