apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.global.name }}-service
  labels:
    app: {{ .Values.global.name }}
    env: {{ .Values.global.environment }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.global.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}